service: lambda

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python37
  memorySize: 1536
  timeout: 300

functions:
  main:
    handler: service.handler
    events:
      - http:
          path: /fetch
          method: get